export const QUERY_KEYS = {
  OWNED_OBJECTS: 'OWNED_OBJECTS',
  OWNED_COINS: 'OWNED_COINS',
  COIN_METADATA: 'COIN_METADATA',
  COIN_PRICE: 'COIN_PRICE',
  PORTFOLIO: 'PORTFOLIO',
  POSITIONS_LIST: 'POSITIONS_LIST',
  ASSETS_LIST: 'ASSETS_LIST',
  OPEN_POSITIONS: 'OPEN_POSITIONS',
  POSITION: 'POSITION',
  WALLET_BALANCE: 'WALLET_BALANCE',
} as const;

export const SUI_NETWORK = 'devnet' as const;
export const SUI_COIN_TYPE = '0x2::sui::SUI' as const;
